### PR TITLE
Gnat pro tools

### PR DESCRIPTION
**Pull request by frank-at-adacore**
Convert existing tools training material to RST

### CODE REVIEW

**Comment by leogermond** [comment]
There are >200 files changed, this would not be realistic for anyone to review that. Can you split the PR?

**Comment by frank-at-adacore** [comment]
> There are >200 files changed, this would not be realistic for anyone to review that. Can you split the PR?

This is just a conversion check-in. As I review/re-write/modify each tool, we can do individual reviews

**Comment by leogermond** [comment]
> This is just a conversion check-in. As I review/re-write/modify each tool, we can do individual reviews

Yes that would be great ! This way we can start reviewing and integrating piecewise right away.

**Comment by leogermond** [comment]
Hi Michael, you'll need to split this PR tool-wise, so that I can review pieces by pieces, otherwise it is a very painful process for me.

**Pull request closed without merging**
